# Copyright (c) OpenMMLab. All rights reserved.
"""Evaluate the original SlideChat Stage-2 checkpoint on the TCGA data.

The original checkpoint uses Qwen2.5-7B plus a 512-dimensional LongNet
visual branch.  The input JSON is generated by
``baseline/slidechat/1_remap2pathoverse.py`` and points to CONCH v1 H5 files.
"""

from mmengine.dataset import DefaultSampler
from mmengine.hooks import DistSamplerSeedHook, IterTimerHook, LoggerHook
from torch import bfloat16
from transformers import AutoModelForCausalLM, AutoTokenizer

from xtuner.dataset import LLaVADataset_longnet
from xtuner.dataset.collate_fns import default_collate_fn
from xtuner.dataset.map_fns import llava_map_fn, template_map_fn_factory
from xtuner.evaluation.metrics.pathology_metric import PathologyMetric
from xtuner.model import LLaVAModel_longnet
from xtuner.utils import PROMPT_TEMPLATE

#######################################################################
#                          PART 1  Settings                           #
#######################################################################

llm_name_or_path = '/data/wg_workspace/model_zoo/Qwen2.5-7B'

# This is the same downstream data used by run_xtuner_test_conv_multi_gpu.sh.
test_data_path = (
    '/data/wg_workspace/projects/TCGA/baseline/slidechat/downstream_test_conch_v1.json')
dataset_cache_dir = '/data/wg_workspace/projects/TCGA/.cache/'
work_dir = (
    '/data/wg_workspace/projects/TCGA/test_results/'
    'original_slidechat_all_pathoverse')
test_output_path = work_dir + '/test_results'

prompt_template = PROMPT_TEMPLATE.qwen_chat
max_length = 19600
max_patch_num = 10240
max_new_tokens = 500
batch_size = 1
dataloader_num_workers = 2

#######################################################################
#            PART 2  Model & Tokenizer & Image Processor              #
#######################################################################

tokenizer = dict(
    type=AutoTokenizer.from_pretrained,
    pretrained_model_name_or_path=llm_name_or_path,
    trust_remote_code=True,
    padding_side='right')

model = dict(
    type=LLaVAModel_longnet,
    tokenizer=tokenizer,
    freeze_llm=False,
    hidden_size=512,
    # The checkpoint is loaded by xtuner/tools/test.py through
    # model.pretrained_pth when --deepspeed is used.
    use_activation_checkpointing=False,
    llm=dict(
        type=AutoModelForCausalLM.from_pretrained,
        pretrained_model_name_or_path=llm_name_or_path,
        trust_remote_code=True,
        torch_dtype=bfloat16),
    generation_kwargs=dict(
        max_new_tokens=max_new_tokens,
        do_sample=False),
    stop_words=['<|im_end|>', '<|endoftext|>'])

#######################################################################
#                      PART 3  Dataset & Dataloader                   #
#######################################################################

test_llava_dataset = dict(
    type=LLaVADataset_longnet,
    data_path=test_data_path,
    cache_dir=dataset_cache_dir,
    image_folder='',
    image_path_list=None,
    tokenizer=tokenizer,
    dataset_map_fn=llava_map_fn,
    template_map_fn=dict(
        type=template_map_fn_factory,
        template=prompt_template),
    max_length=max_length,
    max_patch_num=max_patch_num,
    per_image_length=None,
    mode='test',
    input_ids_with_output=True)

test_dataloader = dict(
    batch_size=batch_size,
    num_workers=dataloader_num_workers,
    pin_memory=True,
    dataset=test_llava_dataset,
    sampler=dict(type=DefaultSampler, shuffle=False),
    collate_fn=dict(type=default_collate_fn))

test_evaluator = dict(
    type=PathologyMetric,
    tokenizer=tokenizer,
    output_dir=test_output_path)

#######################################################################
#                           PART 4  Runtime                           #
#######################################################################

test_cfg = dict(type='TestLoop')

default_hooks = dict(
    timer=dict(type=IterTimerHook),
    logger=dict(type=LoggerHook, log_metric_by_epoch=False, interval=10),
    sampler_seed=dict(type=DistSamplerSeedHook),
)

env_cfg = dict(
    cudnn_benchmark=False,
    mp_cfg=dict(mp_start_method='fork', opencv_num_threads=0),
    dist_cfg=dict(backend='nccl'),
)

visualizer = None
log_level = 'INFO'
load_from = None
resume = False
randomness = dict(seed=42, deterministic=False)
log_processor = dict(by_epoch=False)
